NaturaUrquiza/Controllers/AdministracionController.cs
using System.Globalization;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using Dominio.Comandos;
using Dominio.Consultas;
using Dominio.Dto;
using Microsoft.Web.Mvc;
using NaturaUrquiza.Helpers;
using Servicios;

namespace NaturaUrquiza.Controllers
{
    public class AdministracionController : Controller
    {
        private readonly IServicioRepositorio servicio;
        private readonly IServicioComandos servicioComandos;

        public AdministracionController(IServicioRepositorio servicio, IServicioComandos servicioComandos)
        {
            this.servicio = servicio;
            this.servicioComandos = servicioComandos;
        }

        public ActionResult Index(string filtro = "", int pagina = 1, string ordenarPor = "Id", DirOrden dirOrden = DirOrden.Asc)
        {
            ListQuery(filtro, pagina, ordenarPor, dirOrden);
            return View((object)filtro);
        }

        [AjaxOnly]
        [ActionName("Index")]
        public ActionResult Listar(string filtro = "", int pagina = 1, string ordenarPor = "Id", DirOrden dirOrden = DirOrden.Asc)
        {
            ListQuery(filtro, pagina, ordenarPor, dirOrden);
            return View("Listar", (object)filtro);
        }

        private void ListQuery(string filtro, int pagina, string ordenarPor, DirOrden dirOrden)
        {
            var paginacion = new Paginacion(ordenarPor, dirOrden, pagina, 10);

            ViewBag.Items = servicio.ListarProductos(filtro,0,paginacion);
        }

        public ActionResult Crear()
        {
            SetearVista();
            return View();
        }

        [HttpPost]
        public ActionResult Crear(ProductoDto model)
        {
            if (ModelState.IsValid)
            {
                var resultado = servicioComandos.Ejecutar(new CrearProducto { Dto = model });
                if (!resultado.HayErrores)
                {
                    return new AjaxEditSuccessResult();
                }
                ModelState.AgregarErrores(resultado);
            }
            SetearVista();
            return View(model);
        }

        public ActionResult Modificar(int id)
        {
            var choferAModificar = servicio.ObtenerProducto(id);
            SetearVista();
            return View(choferAModificar);
        }

        [HttpPost]
        public ActionResult Modificar(ProductoDto model)
        {
            if (ModelState.IsValid)
            {
                var resultado = servicioComandos.Ejecutar(new ModificarProducto { Dto = model });
                if (!resultado.HayErrores)
                {
                    return new AjaxEditSuccessResult();
                }
                ModelState.AgregarErrores(resultado);
            }
            SetearVista();
            return View(model);
        }

        [HttpPost]
        public ActionResult Eliminar(int id)
        {
            var resultado = servicioComandos.Ejecutar(new EliminarProducto { Id = id });
            return Content(!resultado.HayErrores ? "true" : resultado.Errores.Values.First());
        }

        private void SetearVista()
        {                                           
            ViewBag.Lineas = servicio.ListarLineas().OrderBy(x => x.Nombre).ToSelectList(x => x.Id.ToString(CultureInfo.InvariantCulture),x=> x.Nombre);
            ViewBag.Tipos = servicio.ListarTipos().OrderBy(x => x.Nombre).ToSelectList(x => x.Id.ToString(CultureInfo.InvariantCulture), x => x.Nombre);
        }
    }
}

NaturaUrquiza/Controllers/NaturaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Runtime.Serialization.Json;
using System.Text;
using System.Web.Mvc;
using Dominio.Consultas;
using Dominio.Dto;
using Microsoft.Web.Mvc;
using Servicios;

namespace NaturaUrquiza.Controllers
{
    public class NaturaController : Controller
    {
        private IServicioRepositorio _servicio;
        public NaturaController(IServicioRepositorio servcio)
        {
            _servicio = servcio;
        }

        public ActionResult Index(string filtro = "",int lineaId = 0, int pagina = 1, string ordenarPor = "Prioridad", DirOrden dirOrden = DirOrden.Asc)
        {
            ListQuery(filtro, lineaId, pagina, ordenarPor, dirOrden);
            return View();
        }

        [AjaxOnly]
        [ActionName("Index")]
        public ActionResult Listar(string filtro = "", int lineaId = 0, int pagina = 1, string ordenarPor = "Prioridad", DirOrden dirOrden = DirOrden.Asc)
        {
            ListQuery(filtro, lineaId, pagina, ordenarPor, dirOrden);
            return View("Listar", (object)filtro);
        }

        private void ListQuery(string filtro, int lineaId, int pagina, string ordenarPor, DirOrden dirOrden)
        {
            var paginacion = new Paginacion(ordenarPor, dirOrden, pagina, 9);
            ViewBag.Productos = _servicio.ListarProductos(filtro, lineaId,paginacion);
        }

        public ActionResult Ver(int id)
        {
            return View(_servicio.ObtenerProducto(id));
        }

        [HttpPost]
        public ActionResult Upload()
        {
            // Get a reference to the file that our jQuery sent.  Even with multiple files, they will all be their own request and be the 0 index
            var file = Request.Files[0];

            // do something with the file in this space 
            var pic = Path.GetFileName(file.FileName.Replace(' ', '-'));
            var path = Path.Combine(Server.MapPath("~/images/profile"), pic);
            // file is uploaded
            file.SaveAs(path);

            // end of file doinge
            return Json(new {HttpStatusCode.OK});
        }

        [HttpPost]
        public ActionResult Comprar(CompraDto dto)
        {
            if (ModelState.IsValid)
            {
                EnviarMailVendedor(dto);
                EnviarMailComprador(dto);
                return new AjaxEditSuccessResult();
            }
            return View("Comprar");
        }

        private void EnviarMailVendedor(CompraDto dto)
        {
            var js = new DataContractJsonSerializer(typeof(ProductoDto[]));
            var ms = new MemoryStream(Encoding.Unicode.GetBytes(dto.Productos));
            var productos = js.ReadObject(ms) as ProductoDto[];

            var fromAddress = new MailAddress("romina.c.lozano@gmail.com", "Romina");
            var to = new MailAddress("aa.olivera09@gmail.com", "ale");
            const string fromPassword = "alejandro7";
            var subject = "Compra " + dto.Nombre + " " + DateTime.Now.ToShortDateString();
            var body = String.Format(
@"<div><b>Nombre:</b>   {0}</div>
<div><b>Telefono:</b>   {1}</div>
<div><b>Mail:</b>   {2}</div>
<div><b>Productos:</b></div> 
<div style='padding-left:5em'>{3}</div>
<div><b>Total: </b>${4}</div>", dto.Nombre, dto.Telefono, dto.Mail, productos.Select(x => "<div><b>" + x.Codigo + " - " + x.Nombre + "</b></div><div style='padding-left:2em'>" + x.PrecioVisible + "</div>").Aggregate((current, next) => current + next), productos.Sum(x => x.PrecioPromocional.HasValue ? x.PrecioPromocional : x.Precio));

            EnviarMAil(fromAddress, fromPassword, to, subject, body);
        }

        private void EnviarMailComprador(CompraDto dto)
        {
            var js = new DataContractJsonSerializer(typeof(ProductoDto[]));
            var ms = new MemoryStream(Encoding.Unicode.GetBytes(dto.Productos));
            var productos = js.ReadObject(ms) as ProductoDto[];

            var fromAddress = new MailAddress("romina.c.lozano@gmail.com", "Romina");
            var to = new MailAddress(dto.Mail, dto.Nombre);
            const string fromPassword = "alejandro7";
            var subject = "Confirmación de compra " + DateTime.Now.ToShortDateString();
            var body = String.Format(
@"<div>Estimada/o {0},</div>
<div>Has seleccionado los productos:</div> 
<div style='padding-left:5em'>{1}</div>
<div style='padding-left:7em'><b>Total: </b>${2}</div>
<br/>
<div>En breve nos pondremos en contacto con usted para confirmar la venta.
Cualquier duda y/o consulta, no dude en comunicarse conmigo al telefono: 15-XXXX-XXXX.
Desde ya, muchas gracias por elegirnos.</div>", dto.Nombre, productos.Select(x => "<div><b>" + x.Nombre + "</b></div><div style='padding-left:2em'>" + x.PrecioVisible + "</div>").Aggregate((current, next) => current + next), productos.Sum(x => x.PrecioPromocional.HasValue ? x.PrecioPromocional : x.Precio));

            EnviarMAil(fromAddress, fromPassword, to, subject, body);
        }

        private static void EnviarMAil(MailAddress fromAddress, string fromPassword, MailAddress to, string subject, string body)
        {
            var smtp = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    UseDefaultCredentials = false,
                    Credentials = new NetworkCredential(fromAddress.Address, fromPassword)
                };
            using (var message = new MailMessage(fromAddress, to)
                {
                    Subject = subject,
                    Body = body,
                    IsBodyHtml = true
                })
            {
                smtp.Send(message);
            }
        }
    }
}

NaturaUrquiza/Views/Administracion/Crear.cshtml
@using Dominio.Recursos
@model Dominio.Dto.ProductoDto
@{
    Layout = null;
    ViewBag.Title = Textos.Producto_Crear;
}
<script type="text/javascript" src="~/Scripts/jQuery.FileUpload/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="~/Scripts/jQuery.FileUpload/jquery.fileupload.js"></script>
@Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript" src="@Url.Content("~/scripts/administracion.crear.js")"></script>
@Html.Hidden("urlUpdate",Url.Action("Upload","Natura"))

@using (Ajax.BeginForm("Crear", "Administracion", new AjaxOptions(), new { @class = "form-horizontal", data_dialogo_titulo = Textos.Producto_Crear, enctype = "multipart/form-data" }))
{
    @Html.Partial("_CrearModificar", Model)
}

NaturaUrquiza/Views/Administracion/Index.cshtml
@using Dominio.Recursos
@{
    ViewBag.Title = Textos.Administracion_Titulo;
}
<br/>
<div class="row">
    <div class="col-xs-12 bordeGris">
        @using (Ajax.BeginForm("Index", null, new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.Replace, UpdateTargetId = "gridContainer" }, new { id = "search-form", @class = "form-horizontal" }))
        {
            <input type="text" name="filtro" class=""/>
            <button type="submit" class="btn">@Textos.Filtrar</button>
            @Html.ActionLink(Textos.Nuevo, "Crear", "Administracion", null, new { @class = "ajax-editar-link btn btn-primary pull-right" })
        }
    </div>
</div>
<div id="gridContainer">
    @Html.Partial("Listar")
</div>

NaturaUrquiza/Views/Administracion/Listar.cshtml
@using Dominio.Consultas
@using Dominio.Dto
@using Dominio.Recursos
@using NaturaUrquiza.Helpers
@{
    Layout = null;
    var items = (ListaPaginada<ProductoDto>) ViewBag.Items;
}

<style>
    th {
        font-size: 1em;
    }
</style>
@Html.Grilla(items,
    grilla => grilla.Columns(
    grilla.ColumnaEliminarModificar(Html, "Administracion"),
    grilla.Columna("Puntos", Textos.Puntos),
    grilla.Columna("Nombre", Textos.Nombre),
    grilla.Columna("Precio", Textos.Precio),
    grilla.Columna("PrecioPromocional", Textos.PrecioPromocional),
    grilla.Columna("Linea.Nombre", Textos.Linea, x => x.Linea),
    grilla.Columna("TipoProducto.Nombre", Textos.Tipo, x => x.TipoProducto)
    ))

NaturaUrquiza/Views/Administracion/Modificar.cshtml
@using Dominio.Recursos
@model Dominio.Dto.ProductoDto
@{
    Layout = null;
    ViewBag.Title = Textos.Producto_Modificar;
}


<script type="text/javascript" src="~/Scripts/jQuery.FileUpload/jquery.iframe-transport.js"></script>
<script type="text/javascript" src="~/Scripts/jQuery.FileUpload/jquery.fileupload.js"></script>
@Scripts.Render("~/bundles/jqueryval")
<script type="text/javascript" src="@Url.Content("~/scripts/administracion.modificar.js")"></script>
@Html.Hidden("urlUpdate",Url.Action("Upload","Natura"))
@using (Ajax.BeginForm("Modificar", "Administracion", new AjaxOptions(), new { @class = "form-horizontal", data_dialogo_titulo = Textos.Producto_Modificar, enctype = "multipart/form-data" }))
{
    @Html.Partial("_CrearModificar", Model)
}

NaturaUrquiza/Views/Administracion/_CrearModificar.cshtml
@model Dominio.Dto.ProductoDto
@{
    ViewBag.Title = "_CrearModificar";
    var tipos = (List<SelectListItem>)ViewBag.Tipos;
    var lineas = (List<SelectListItem>)ViewBag.Lineas;
}

<style>
    .form-group {
        margin-bottom: 5px;
    }
</style> 
<script type="text/javascript">
    $.validator.methods.number = function(value, element) {
        value = floatValue(value);
        return this.optional(element) || !isNaN(value);
    };
    $.validator.methods.range = function(value, element, param) {
        value = floatValue(value);
        return this.optional(element) || (value >= param[0] && value <= param[1]);
    };
 
    function floatValue(value) {
        return parseFloat(value.replace(",", "."));
    }

</script>

@Html.ValidationSummary(true)
<div class="form-group">
    @Html.LabelFor(model => model.Nombre, new {@class = "control-label col-sm-4"})
    <div class="col-sm-6">
        @Html.TextBoxFor(model => model.Nombre, new {@class = "form-control"})
        @Html.ValidationMessageFor(model => model.Nombre)
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Codigo, new {@class = "control-label col-sm-4"})
    <div class="col-sm-6">
        @Html.TextBoxFor(model => model.Codigo, new {@class = "form-control"})
        @Html.ValidationMessageFor(model => model.Codigo)
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Descripcion, new {@class = "control-label col-sm-4"})
    <div class="col-sm-6">
        @Html.TextAreaFor(model => model.Descripcion, new {@class = "form-control"})
        @Html.ValidationMessageFor(model => model.Descripcion)
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.DescripcionCorta, new {@class = "control-label col-sm-4"})
    <div class="col-sm-6">
        @Html.TextBoxFor(model => model.DescripcionCorta, new {@class = "form-control"})
        @Html.ValidationMessageFor(model => model.DescripcionCorta)
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Precio, new {@class = "control-label col-sm-4"})
    <div class="col-sm-6">
        @Html.TextBoxFor(model => model.Precio, new {@class = "form-control"})
        @Html.ValidationMessageFor(model => model.Precio)
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.PrecioPromocional, new {@class = "control-label col-sm-4"})
    <div class="col-sm-6">
        @Html.TextBoxFor(model => model.PrecioPromocional, new {@class = "form-control"})
        @Html.ValidationMessageFor(model => model.PrecioPromocional)
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Puntos, new {@class = "control-label col-sm-4"})
    <div class="col-sm-6">
        @Html.TextBoxFor(model => model.Puntos, new {@class = "form-control"})
        @Html.ValidationMessageFor(model => model.Puntos)
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Prioridad, new {@class = "control-label col-sm-4"})
    <div class="col-sm-6">
        @Html.TextBoxFor(model => model.Prioridad, new {@class = "form-control"})
        @Html.ValidationMessageFor(model => model.Prioridad)
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.Linea, new {@class = "control-label col-sm-4"})
    <div class="col-sm-6">
        @Html.DropDownListFor(model => model.LineaId, lineas, new {@class = "form-control"})
        @Html.ValidationMessageFor(model => model.LineaId)
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.TipoProducto, new {@class = "control-label col-sm-4"})
    <div class="col-sm-6">
        @Html.DropDownListFor(model => model.TipoProductoId, tipos, new {@class = "form-control"})
        @Html.ValidationMessageFor(model => model.TipoProductoId)
    </div>
</div>
<div class="form-group">
    @Html.LabelFor(model => model.FotoPath, new { @class = "control-label col-sm-4" })
    @Html.HiddenFor(model => model.FotoPath)


    <div class="col-sm-6">
        @if (Model != null && !String.IsNullOrEmpty(Model.FotoPath))
        {
            <h5>Imagen Actual: <small>@Html.DisplayFor(model => model.FotoPath)</small></h5>
        }
        <div id="fileimput">
            <input type="file" id="fileupload" name="fileupload" accept="image/*" style="width: 100%;">
        </div>
        <div class="well hide" id="filelistholder">
        </div>
        @Html.ValidationMessageFor(model => model.FotoPath)
    </div>
</div>